data:
  name: v2_35
  data_folder: './egs/speech_commands'
  labels: ['hap','exc','sad','ang','neu']
  scp_file: ./egs/iemocap/fbank/train_sp/feats.scp
  text_file: ./egs/iemocap/fbank/train_sp/text
  cmvn_file: ./egs/iemocap/fbank/train_sp/global_cmvn

dataset_conf:
  kaldi_offline: True
  kaldi_offline_conf:
    feat_dim: 40
    spec_augment: False
    spec_augment_conf:
        warp_for_time: False
        num_t_mask: 2
        num_f_mask: 2
        max_t: 10
        max_f: 5
        max_w: 10
    spec_substitute: False
    spec_substitute_conf:
      max_t: 10
      num_t_sub: 2
    max_frames: 750
    max_tokens: 50
    fixed_feats: True


model:
  audio_only: True
  audio_model_settings:
    model_type: emotion_transformer
    model_params:
      input_size: [750,40]
      patch_size: [5,40]
      channels: 1
      num_classes: 4
      dim: 64
      depth: 12
      dim_head: 64
      heads: 4
      mlp_dim: 256
      dropout: 0.1
      emb_dropout: 0.1    
      pool: 'mean'
  
  text_only: False
  multi_modal: False
    
train:
  optimizer_type: adam
  optimizer:
    lr: 0.001
    betas: [0.9, 0.98]
    eps: 1.0e-9
    weight_decay: 1.0e-6
    amsgrad: False
  scheduler_type: transformer
  scheduler:
    model_size: 64
    warmup_steps: 1000
    factor: 0.8
  
  clip_grad: 5
  epochs: 80
  accum_steps: 4
  grad_noise: 0.0
  load_model: False
  batch_size: 10
  model_dir: emotion_transformer
  exp_dir: './egs/iemocap/exp'
  
eval:
  average_model:
    dst_model: 'average_final.pt'
    num: 5
    val_best: True
    min_epoch: 5
    max_epoch: 10000